+define+NMU_SAM_CHECKS
+incdir+deps/common_cells-v2.0.0-beta.3/include
+incdir+deps/axi-0.39.7/include
+incdir+deps/common_cells-1.37.0/include
repo/specgen/generated/sv/ni_params_pkg.sv
repo/specgen/generated/sv/ni_signals_pkg.sv
repo/specgen/generated/sv/ni_flit_pkg.sv
topology_pkg.sv
repo/rtl/common/ni_types_pkg.sv
deps/common_cells-v2.0.0-beta.3/src/cc_pkg.sv
deps/common_cells-v2.0.0-beta.3/src/cc_binary_to_gray.sv
deps/common_cells-v2.0.0-beta.3/src/cc_gray_to_binary.sv
deps/common_cells-v2.0.0-beta.3/src/cc_spill_register_flushable.sv
deps/common_cells-v2.0.0-beta.3/src/cc_spill_register.sv
deps/common_cells-v2.0.0-beta.3/src/cc_stream_register.sv
deps/tech_cells_generic-v0.2.14/src/rtl/tc_sync.sv
deps/common_cells-v2.0.0-beta.3/src/cc_cdc_fifo_gray.sv
deps/common_cells-v2.0.0-beta.3/src/cc_addr_decode_dync.sv
deps/common_cells-v2.0.0-beta.3/src/cc_addr_decode.sv
repo/rtl/common/axi_async_fifo.sv
repo/rtl/common/ni_sam.sv
repo/rtl/common/stream_register.sv
repo/rtl/nmu/request_fifo/request_fifo.sv
repo/rtl/nmu/sam/sam.sv
deps/common_cells-1.37.0/src/cf_math_pkg.sv
deps/common_cells-1.37.0/src/lzc.sv
deps/common_cells-1.37.0/src/rr_arb_tree.sv
deps/axi-0.39.7/src/axi_pkg.sv
deps/common_cells-v2.0.0-beta.3/src/cc_credit_counter.sv
deps/common_cells-v2.0.0-beta.3/src/cc_fifo.sv
repo/rtl/common/axi_if.sv
repo/rtl/nmu/ordering/reorder_storage.sv
repo/rtl/nmu/ordering/ordering.sv
repo/rtl/nmu/channel_assign/tx_channel_assign.sv
repo/rtl/nmu/request_path/write_context.sv
repo/rtl/common/tx_credit_buffer.sv
repo/rtl/common/tx_vc_arbiter.sv
repo/rtl/nmu/request_packetize/request_packetize.sv
repo/rtl/common/rx_credit_buffer.sv
repo/rtl/nmu/channel_assign/rx_channel_assign.sv
repo/rtl/nmu/channel_assign/rx_vc_arbiter.sv
repo/rtl/nmu/response_depacketize/response_depacketize.sv
repo/rtl/nmu/response_fifo/response_fifo.sv
repo/rtl/nmu/response_path/response_path.sv
repo/rtl/nmu/request_path/request_path.sv
repo/rtl/nmu/top/nmu.sv
repo/sim/dv/nmu_sam_burst_checker.sv
deps/tech_cells_generic-v0.2.14/src/rtl/tc_clk.sv
deps/common_cells-v2.0.0-beta.3/src/cc_rstgen_bypass.sv
deps/common_verification-0.2.5/src/rand_id_queue.sv
-v deps/axi-0.39.7/src/axi_intf.sv
deps/axi-0.39.7/src/axi_test.sv
