// ----------------------------------------------------------------------------
// AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT
// Source:    specgen/generated/json/ni_signals.json
// Source SHA: c25cfdfac37f
// Generator version: v1.0.0
// ----------------------------------------------------------------------------
`timescale 1ns/1ps

`ifndef NI_SIGNALS_PKG_SVH
`define NI_SIGNALS_PKG_SVH

package ni_signals_pkg;

  // Reset initializer constants for output signals.
  // Input signals (external_driven) have no reset value defined here.

  localparam int unsigned AXI_BID_O_RESET = 0;
  localparam int unsigned AXI_BRESP_O_RESET = 0;
  localparam int unsigned AXI_BUSER_O_RESET = 0;
  localparam int unsigned AXI_RID_O_RESET = 0;
  localparam int unsigned AXI_RDATA_O_RESET = 0;
  localparam int unsigned AXI_RRESP_O_RESET = 0;
  localparam int unsigned AXI_RLAST_O_RESET = 0;
  localparam int unsigned AXI_RUSER_O_RESET = 0;
  localparam int unsigned NOC_REQ_VALID_O_RESET = 0;
  localparam int unsigned NOC_REQ_FLIT_O_RESET = 0;
  localparam int unsigned NOC_RSP_CREDIT_O_RESET = 0;
  localparam int unsigned CSR_BID_O_RESET = 0;
  localparam int unsigned CSR_BRESP_O_RESET = 0;
  localparam int unsigned CSR_BUSER_O_RESET = 0;
  localparam int unsigned CSR_RID_O_RESET = 0;
  localparam int unsigned CSR_RDATA_O_RESET = 0;
  localparam int unsigned CSR_RRESP_O_RESET = 0;
  localparam int unsigned CSR_RLAST_O_RESET = 0;
  localparam int unsigned CSR_RUSER_O_RESET = 0;
  localparam int unsigned NOC_REQ_CREDIT_O_RESET = 0;
  localparam int unsigned NOC_RSP_VALID_O_RESET = 0;
  localparam int unsigned NOC_RSP_FLIT_O_RESET = 0;
  localparam int unsigned AXI_AWID_O_RESET = 0;
  localparam int unsigned AXI_AWADDR_O_RESET = 0;
  localparam int unsigned AXI_AWLEN_O_RESET = 0;
  localparam int unsigned AXI_AWSIZE_O_RESET = 0;
  localparam int unsigned AXI_AWBURST_O_RESET = 0;
  localparam int unsigned AXI_AWCACHE_O_RESET = 0;
  localparam int unsigned AXI_AWLOCK_O_RESET = 0;
  localparam int unsigned AXI_AWPROT_O_RESET = 0;
  localparam int unsigned AXI_AWREGION_O_RESET = 0;
  localparam int unsigned AXI_AWUSER_O_RESET = 0;
  localparam int unsigned AXI_AWQOS_O_RESET = 0;
  localparam int unsigned AXI_WDATA_O_RESET = 0;
  localparam int unsigned AXI_WSTRB_O_RESET = 0;
  localparam int unsigned AXI_WLAST_O_RESET = 0;
  localparam int unsigned AXI_WUSER_O_RESET = 0;
  localparam int unsigned AXI_ARID_O_RESET = 0;
  localparam int unsigned AXI_ARADDR_O_RESET = 0;
  localparam int unsigned AXI_ARLEN_O_RESET = 0;
  localparam int unsigned AXI_ARSIZE_O_RESET = 0;
  localparam int unsigned AXI_ARBURST_O_RESET = 0;
  localparam int unsigned AXI_ARCACHE_O_RESET = 0;
  localparam int unsigned AXI_ARLOCK_O_RESET = 0;
  localparam int unsigned AXI_ARPROT_O_RESET = 0;
  localparam int unsigned AXI_ARREGION_O_RESET = 0;
  localparam int unsigned AXI_ARUSER_O_RESET = 0;
  localparam int unsigned AXI_ARQOS_O_RESET = 0;

  // AXI channel payloads. VALID and READY are independent stream ports.
  // Fields are declared MSB-to-LSB; packed index zero is the first protocol field.
  typedef struct packed {
    logic [ni_params_pkg::AXI_AWUSER_WIDTH-1:0] awuser;
    logic [3:0]                                 awqos;
    logic [3:0]                                 awregion;
    logic [2:0]                                 awprot;
    logic                                       awlock;
    logic [3:0]                                 awcache;
    logic [1:0]                                 awburst;
    logic [2:0]                                 awsize;
    logic [7:0]                                 awlen;
    logic [ni_params_pkg::AXI_ADDR_WIDTH-1:0]   awaddr;
    logic [ni_params_pkg::AXI_ID_WIDTH-1:0]     awid;
  } axi_aw_t;
  typedef struct packed {
    logic [ni_params_pkg::AXI_AWUSER_WIDTH-1:0] awuser;
    logic [3:0]                                 awqos;
    logic [3:0]                                 awregion;
    logic [2:0]                                 awprot;
    logic                                       awlock;
    logic [3:0]                                 awcache;
    logic [1:0]                                 awburst;
    logic [2:0]                                 awsize;
    logic [7:0]                                 awlen;
    logic [ni_params_pkg::AXI_ADDR_WIDTH-1:0]   awaddr;
    logic [ni_params_pkg::NOC_ID_WIDTH-1:0]     awid;
  } noc_axi_aw_t;
  typedef struct packed {
    logic [ni_params_pkg::AXI_DATA_WIDTH-1:0]   wdata;
    logic [ni_params_pkg::AXI_DATA_WIDTH/8-1:0] wstrb;
    logic                                       wlast;
  } axi_w_t;
  typedef struct packed {
    logic [ni_params_pkg::AXI_DATA_WIDTH-1:0]   wdata;
    logic [ni_params_pkg::AXI_DATA_WIDTH/8-1:0] wstrb;
    logic                                       wlast;
  } noc_axi_w_t;
  typedef struct packed {
    logic [1:0]                             bresp;
    logic [ni_params_pkg::AXI_ID_WIDTH-1:0] bid;
  } axi_b_t;
  typedef struct packed {
    logic [1:0]                             bresp;
    logic [ni_params_pkg::NOC_ID_WIDTH-1:0] bid;
  } noc_axi_b_t;
  typedef struct packed {
    logic [3:0]                               arqos;
    logic [3:0]                               arregion;
    logic [2:0]                               arprot;
    logic                                     arlock;
    logic [3:0]                               arcache;
    logic [1:0]                               arburst;
    logic [2:0]                               arsize;
    logic [7:0]                               arlen;
    logic [ni_params_pkg::AXI_ADDR_WIDTH-1:0] araddr;
    logic [ni_params_pkg::AXI_ID_WIDTH-1:0]   arid;
  } axi_ar_t;
  typedef struct packed {
    logic [3:0]                               arqos;
    logic [3:0]                               arregion;
    logic [2:0]                               arprot;
    logic                                     arlock;
    logic [3:0]                               arcache;
    logic [1:0]                               arburst;
    logic [2:0]                               arsize;
    logic [7:0]                               arlen;
    logic [ni_params_pkg::AXI_ADDR_WIDTH-1:0] araddr;
    logic [ni_params_pkg::NOC_ID_WIDTH-1:0]   arid;
  } noc_axi_ar_t;
  typedef struct packed {
    logic [ni_params_pkg::AXI_DATA_WIDTH-1:0] rdata;
    logic [1:0]                               rresp;
    logic [ni_params_pkg::AXI_ID_WIDTH-1:0]   rid;
    logic                                     rlast;
  } axi_r_t;
  typedef struct packed {
    logic [ni_params_pkg::AXI_DATA_WIDTH-1:0] rdata;
    logic [1:0]                               rresp;
    logic [ni_params_pkg::NOC_ID_WIDTH-1:0]   rid;
    logic                                     rlast;
  } noc_axi_r_t;

  // AXI wrap-port aggregates (widths fixed-default).
  typedef struct packed {
    logic [ni_params_pkg::AXI_ID_WIDTH-1:0]     awid;
    logic [ni_params_pkg::AXI_ADDR_WIDTH-1:0]   awaddr;
    logic [7:0]                                 awlen;
    logic [2:0]                                 awsize;
    logic [1:0]                                 awburst;
    logic                                       awlock;
    logic [3:0]                                 awcache;
    logic [2:0]                                 awprot;
    logic [3:0]                                 awqos;
    logic [3:0]                                 awregion;
    logic [ni_params_pkg::AXI_AWUSER_WIDTH-1:0] awuser;
    logic                                       awvalid;
    logic [ni_params_pkg::AXI_DATA_WIDTH-1:0]   wdata;
    logic [ni_params_pkg::AXI_DATA_WIDTH/8-1:0] wstrb;
    logic                                       wlast;
    logic                                       wvalid;
    logic                                       bready;
    logic [ni_params_pkg::AXI_ID_WIDTH-1:0]     arid;
    logic [ni_params_pkg::AXI_ADDR_WIDTH-1:0]   araddr;
    logic [7:0]                                 arlen;
    logic [2:0]                                 arsize;
    logic [1:0]                                 arburst;
    logic                                       arlock;
    logic [3:0]                                 arcache;
    logic [2:0]                                 arprot;
    logic [3:0]                                 arqos;
    logic [3:0]                                 arregion;
    logic                                       arvalid;
    logic                                       rready;
  } axi_req_t;
  typedef struct packed {
    logic                                     awready;
    logic                                     wready;
    logic [ni_params_pkg::AXI_ID_WIDTH-1:0]   bid;
    logic [1:0]                               bresp;
    logic                                     bvalid;
    logic                                     arready;
    logic [ni_params_pkg::AXI_ID_WIDTH-1:0]   rid;
    logic [ni_params_pkg::AXI_DATA_WIDTH-1:0] rdata;
    logic [1:0]                               rresp;
    logic                                     rlast;
    logic                                     rvalid;
  } axi_rsp_t;

endpackage

`endif // NI_SIGNALS_PKG_SVH
